In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
PERIOD = "1y"

In [4]:
WIG20 = ["ACP", "ALE", "CCC", "CDR", "CPS", "DNP", "JSW", "KGH", "KRU", "KTY", "LPP", "MBK", "OPL", "PCO", "PEO", "PGE", "PKN", "PKO", "PZU", "SPL"]

WIG40 = ["11B", "ALR", "APR", "ASB", "ATT", "BDX", "BFT", "BHW", "BMC", "CAR", "CIE", "CMR", "DAT", "DOM", "DVL", "EAT", "ENA", "EUR", "FMF", "GPP",
         "GPW", "HUG", "ING", "KER", "LVC", "LWB", "MAB", "MBR", "MIL", "MRC", "NEU", "PEP", "PKP", "SLV", "STH", "TEN", "TPE", "WPL", "XTB", "ZEP"]

WIG80 = ["1AT", "ABE", "ACG", "ACT", "AGO", "AMB", "AMC", "AML", "APT", "ARH", "ASE", "AST", "ATC", "ATG", "BIO", "BML", "BNP", "BOS", "BOW", "BRS",
         "CAV", "CIG", "CLE", "CLN", "CMP", "COG", "CRJ", "CTX", "DCR", "ECH", "ENT", "ERB", "FRO", "FTE", "GRN", "GTN", "IMC", "INK", "KGN", "LBW",
         "MCI", "MLS", "MOC", "MRB", "NWG", "OND", "OPN", "PBX", "PCF", "PCR", "PEN", "PHN", "PLW", "PXM", "R22", "RBW", "RFK", "RVU", "RWL", "SCP",
         "SEN", "SGN", "SHO", "SKA", "SNK", "SNT", "SNX", "STP", "STX", "TIM", "TOA", "TOR", "UNT", "VGO", "VOT", "VOX", "VRC", "VRG", "WLT", "WWL"]

TICKERS = WIG80 + WIG40 + WIG20

dfs_wig20 = []
dfs_wig40 = []
dfs_wig80 = []

for company in WIG20:
    ticker = yf.Ticker(company + ".WA")
    dfs_wig20.append(ticker.history(period=PERIOD))

for company in WIG40:
    ticker = yf.Ticker(company + ".WA")
    dfs_wig40.append(ticker.history(period=PERIOD))

for company in WIG80:
    ticker = yf.Ticker(company + ".WA")
    dfs_wig80.append(ticker.history(period=PERIOD))

FMF.WA: No data found, symbol may be delisted
LVC.WA: No data found, symbol may be delisted
AML.WA: No data found, symbol may be delisted
BML.WA: No data found, symbol may be delisted
R22.WA: No data found, symbol may be delisted


In [5]:
CURRENCIES = ["EURUSD", "USDPLN", "EURPLN", "GBPUSD", "USDJPY"]

dfs_currencies = []
for currency in CURRENCIES:
    c = yf.Ticker(currency+"=X")
    dfs_currencies.append(c.history(period=PERIOD))

In [6]:
INDEXES = ["^GSPC", "^IXIC", "^GDAXI", "^FTSE", "^N225"]

dfs_indexes = []
for index in INDEXES:
    i = yf.Ticker(index)
    dfs_indexes.append(i.history(period=PERIOD))

In [7]:
NATURAL_RESOURCES = ["CL=F", "CB=F", "NG=F", "GC=F", "SI=F", "HG=F", "ZC=F", "HDG=F"]

dfs_resources = []
for resource in NATURAL_RESOURCES:
    n = yf.Ticker("GC=F")
    dfs_resources.append(n.history(period=PERIOD))

In [8]:
PRICES = TICKERS + NATURAL_RESOURCES + CURRENCIES + INDEXES

dfs = dfs_wig20 + dfs_wig40 + dfs_wig80 + dfs_resources + dfs_currencies + dfs_indexes

In [9]:
len(PRICES)

158

In [28]:
ohlcv = []

for df in dfs:
    df = df[["Open", "High", "Low", "Close", "Volume"]]
    ohlcv.append(df)

In [88]:
idx = ohlcv[0].index

#Hacky, idk why this does not work

for df in ohlcv[1:133]:
    if df.index.size > 0:
        idx = idx.intersection(df.index)

251 251
251 251
251 251
251 251
251 251
251 251
251 252
251 251
251 251
251 251
251 251
251 251
251 251
251 251
251 252
251 251
251 252
251 251
251 251
251 251
251 251
251 251
251 251
251 251
251 251
251 252
251 251
251 251
251 251
250 252
250 251
250 251
250 251
250 251
250 251
250 251
250 252
250 251
250 251
250 251
250 252
250 251
250 252
250 251
250 251
250 252
250 251
250 251
250 251
250 251
250 251
250 253
250 251
250 251
250 251
250 251
250 252
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 252
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 252
250 251
250 251
250 252
250 251
250 251
250 252
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251
250 251


In [89]:
common = []

for df in ohlcv:
    common.append(df.reindex(index=idx))

In [91]:
len(common)

158

158 prices * 5 variables for each day (250 days)

In [112]:
normal = []
names = ["Open", "High", "Low", "Close", "Volume"]

for price in common:
    vec = []
    for value in names:
        curr = price[value]
        mean = curr.mean()
        std = curr.std()

        normalized = (curr - mean) / std
        vec.append(normalized)
    
    normal.append(pd.concat(vec, axis=1, names=names))

In [113]:
len(normal)

158

In [115]:
normal[0]['Close']

Date
2023-01-09 00:00:00+01:00   -0.996601
2023-01-10 00:00:00+01:00   -1.254271
2023-01-11 00:00:00+01:00   -1.671453
2023-01-12 00:00:00+01:00   -1.585562
2023-01-13 00:00:00+01:00   -1.745070
                               ...   
2023-12-29 00:00:00+01:00   -0.891506
2024-01-02 00:00:00+01:00   -1.173183
2024-01-03 00:00:00+01:00   -1.237200
2024-01-04 00:00:00+01:00   -1.288413
2024-01-05 00:00:00+01:00   -0.865900
Name: Close, Length: 250, dtype: float64

In [131]:
dataset = np.nan_to_num(np.swapaxes(np.stack(normal), 0, 1).reshape(250, 158*5), copy=True, nan=0.0)

dataset.shape

(250, 790)

In [165]:
import torch
import torch.nn as nn
import torch.optim as optim

layer = nn.TransformerEncoderLayer(d_model=790, nhead=10)
model = nn.TransformerEncoder(layer, num_layers=3)

optimizer = optim.AdamW(model.parameters())
loss_function = nn.MSELoss()

In [166]:
def src_mask(sz):
  mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
  mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
  
  return mask

In [167]:
class Iter:
    def __init__(self, dataset):
        self.data = dataset
        self.idx = 0

    def inc(self):
        self.idx += 1

        return self.idx

    def __next__(self):
        idx = self.inc()

        if idx >= self.data.shape[0]:
            raise StopIteration
        else:
            return self.data[idx - 1], self.data[idx]

    def __iter__(self):
        return self

In [168]:
train, test = np.array_split(dataset, 2)

print(train.shape, test.shape)

(125, 790) (125, 790)


In [169]:
test_loss_after = []

iter_test = Iter(test)
test_seq = torch.zeros(790).unsqueeze(0)

for x, y in iter_test:
    inp = torch.reshape(torch.tensor(x, dtype=torch.float), (790,)).unsqueeze(0).nan_to_num(nan=0.0)
    test_seq = torch.cat((test_seq, inp), dim=0).nan_to_num(nan=0.0)
    y_hat = model(test_seq, src_mask(790)).squeeze().to(torch.float32)
    y = torch.reshape(torch.tensor(y).to(torch.float32), (790,))
    pred = y_hat[0]
    pred = pred.nan_to_num(nan=0.0)
    y = y.nan_to_num(nan=0.0)

    loss = loss_function(pred[::2], y[::2])

    test_loss_after.append(loss.item())

print("Test loss: ", sum(test_loss_after) / len(test_loss_after))

Test loss:  1.7743169069290161


In [171]:
train_loss = []

iter_train = Iter(train)
train_seq = torch.zeros(790).unsqueeze(0)

for x, y in iter_train:
    optimizer.zero_grad()

    inp = torch.reshape(torch.tensor(x, dtype=torch.float), (790,)).unsqueeze(0).nan_to_num(nan=0.0)
    test_seq = torch.cat((test_seq, inp), dim=0).nan_to_num(nan=0.0)
    y_hat = model(test_seq, src_mask(790)).squeeze().to(torch.float32)
    y = torch.reshape(torch.tensor(y).to(torch.float32), (790,))
    pred = y_hat[0]
    pred = pred.nan_to_num(nan=0.0)
    y = y.nan_to_num(nan=0.0)

    loss = loss_function(pred[::2], y[::2])

    loss.backward()
    optimizer.step()

    train_loss.append(loss.item())

print("Train loss: ", sum(train_loss) / len(train_loss))

Train loss:  0.4181289706499346


In [172]:
test_loss_after = []

iter_test = Iter(test)
test_seq = torch.zeros(790).unsqueeze(0)

for x, y in iter_test:
    inp = torch.reshape(torch.tensor(x, dtype=torch.float), (790,)).unsqueeze(0).nan_to_num(nan=0.0)
    test_seq = torch.cat((test_seq, inp), dim=0).nan_to_num(nan=0.0)
    y_hat = model(test_seq, src_mask(790)).squeeze().to(torch.float32)
    y = torch.reshape(torch.tensor(y).to(torch.float32), (790,))
    pred = y_hat[0]
    pred = pred.nan_to_num(nan=0.0)
    y = y.nan_to_num(nan=0.0)

    loss = loss_function(pred[::2], y[::2])

    test_loss_after.append(loss.item())

print("Test loss: ", sum(test_loss_after) / len(test_loss_after))

Test loss:  1.0440861210227013


No importance masking implemented 